# Generated by Django 2.0.4 on 2018-04-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='', help_text='作者', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='', help_text='分类', max_length=32),
            preserve_default=False,
        ),
    ]
