# Generated by Django 2.0.4 on 2018-04-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=256)),
                ('user_id', models.IntegerField(help_text='用户')),
                ('body', models.TextField(help_text='正文')),
            ],
        ),
    ]
